mod helper_methods;
#[derive(Debug, PartialEq, Eq, Clone, Copy)]
pub enum TokenType {
    TokenLeftParen,
    TokenRightParen,
    TokenLeftCurlyBrace,
    TokenRightCurlyBrace,
    TokenLeftSquareBracket,
    TokenRightSquareBracket,
    TokenSemicolon,
    TokenBang,
    TokenAssign,
    TokenMinus,
    TokenPlus,
    TokenSlash,
    TokenStar,
    TokenNumber,
    TokenIdentifier,
    TokenTrue,
    TokenFalse,
    TokenInt32,
    TokenBool,
    TokenDefine,
    TokenMutable,
    TokenFunction,
    TokenTyping,
    TokenPrint,
    TokenError,
    TokenEOF,
}
impl From<TokenType> for usize {
    fn from(value: TokenType) -> Self {
        match value {
            TokenType::TokenLeftParen => 0,
            TokenType::TokenRightParen => 1,
            TokenType::TokenLeftCurlyBrace => 2,
            TokenType::TokenRightCurlyBrace => 3,
            TokenType::TokenLeftSquareBracket => 4,
            TokenType::TokenRightSquareBracket => 5,
            TokenType::TokenSemicolon => 6,
            TokenType::TokenBang => 7,
            TokenType::TokenAssign => 8,
            TokenType::TokenMinus => 9,
            TokenType::TokenPlus => 10,
            TokenType::TokenSlash => 11,
            TokenType::TokenStar => 12,
            TokenType::TokenNumber => 13,
            TokenType::TokenIdentifier => 14,
            TokenType::TokenTrue => 15,
            TokenType::TokenFalse => 16,
            TokenType::TokenInt32 => 17,
            TokenType::TokenBool => 18,
            TokenType::TokenDefine => 19,
            TokenType::TokenMutable => 20,
            TokenType::TokenFunction => 21,
            TokenType::TokenTyping => 22,
            TokenType::TokenPrint => 23,
            TokenType::TokenError => 24,
            TokenType::TokenEOF => 25,
        }
    }
}
