mod helper_methods;
#[derive(Debug, PartialEq, Eq, Clone, Copy)]
pub enum TokenType {
    TokenLeftParen,
    TokenRightParen,
    TokenMinus,
    TokenPlus,
    TokenSlash,
    TokenStar,
    TokenNumber,
    TokenIdentifier,
    TokenTrue,
    TokenFalse,
    TokenInt32,
    TokenBool,
    TokenSemicolon,
    TokenBang,
    TokenAssign,
    TokenLeftCurlyBrace,
    TokenRightCurlyBrace,
    TokenDefine,
    TokenMutable,
    TokenFunction,
    TokenPrint,
    TokenError,
    TokenEOF,
}
impl From<TokenType> for usize {
    fn from(value: TokenType) -> Self {
        match value {
            TokenType::TokenLeftParen => 0,
            TokenType::TokenRightParen => 1,
            TokenType::TokenMinus => 2,
            TokenType::TokenPlus => 3,
            TokenType::TokenSlash => 4,
            TokenType::TokenStar => 5,
            TokenType::TokenNumber => 6,
            TokenType::TokenIdentifier => 7,
            TokenType::TokenTrue => 8,
            TokenType::TokenFalse => 9,
            TokenType::TokenInt32 => 10,
            TokenType::TokenBool => 11,
            TokenType::TokenSemicolon => 12,
            TokenType::TokenBang => 13,
            TokenType::TokenAssign => 14,
            TokenType::TokenLeftCurlyBrace => 15,
            TokenType::TokenRightCurlyBrace => 16,
            TokenType::TokenDefine => 17,
            TokenType::TokenMutable => 18,
            TokenType::TokenFunction => 19,
            TokenType::TokenPrint => 20,
            TokenType::TokenError => 21,
            TokenType::TokenEOF => 22,
        }
    }
}
